---
swagger: '2.0'
info:
  title: Image Transformation API
  description: |-
    An Image Processing RPC API, which provides endpoints for users to perform various image processing operations. This document is intended for the CPSC 5200-02 lecturer, grader and API Users.
  version: '1.0'
  contact:
    name: DavisRayM
    url: 'https://github.com/DavisRayM'
    email: git@davisraym.com
  license:
    name: MIT
    url: 'https://github.com/DavisRayM/image-transformer/blob/main/LICENSE'
tags:
  - name: ImageTransformer
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/transform:
    post:
      summary: Apply transformations on the supplied image.
      description: |-
        Provides an endpoint for users to perform a combination of image transformation operation on the supplied image.
      operationId: ImageTransformer_transform
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1TransformResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1TransformRequest'
      tags:
        - ImageTransformer
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  transformv1Operation:
    type: object
    properties:
      kind:
        $ref: '#/definitions/v1OperationType'
      arguments:
        type: array
        items:
          type: integer
          format: int32
  v1OperationType:
    type: string
    enum:
      - RotateLeft
      - RotateRight
      - RotateN
      - FlipHorizontally
      - FlipVertically
      - GrayScale
      - Resize
      - Thumbnail
    default: RotateLeft
  v1TransformRequest:
    type: object
    properties:
      imageData:
        type: string
        format: byte
      operation:
        type: array
        items:
          type: object
          $ref: '#/definitions/transformv1Operation'
  v1TransformResponse:
    type: object
    properties:
      imageData:
        type: array
        items:
          type: string
          format: byte
      thumbnailData:
        type: array
        items:
          type: string
          format: byte

